### ISSUE TITLE
Doesn't compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by zero-impact** [Yixin-Hu/TetWild#2]
Installed CGAL with
```
$  sudo apt-get install libcgal-dev libcgal-qt5-dev
```

Cmake completes with no issue, but fails when building `tetwild.cpp` with many errors of the form
```
[ 99%] Building CXX object CMakeFiles/TetWild.dir/tetwild.cpp.o
In file included from /usr/include/CGAL/Constrained_triangulation_2.h:28:0,
                 from /usr/include/CGAL/Constrained_Delaunay_triangulation_2.h:25,
                 from /home/lawson/Workspace/TetWild/SimpleTetrahedralization.cpp:15:
/usr/include/CGAL/Triangulation_2.h: In instantiation of ‘class CGAL::Triangulation_2<CGAL::Epeck, CGAL::Default>’:
/usr/include/CGAL/Constrained_triangulation_2.h:47:7:   required from ‘class CGAL::Constrained_triangulation_2<CGAL::Epeck, CGAL::Default, CGAL::Exact_predicates_tag>’
/usr/include/CGAL/Constrained_Delaunay_triangulation_2.h:63:7:   required from ‘class CGAL::Constrained_Delaunay_triangulation_2<CGAL::Epeck, CGAL::Default, CGAL::Exact_predicates_tag>’
/home/lawson/Workspace/TetWild/SimpleTetrahedralization.cpp:19:12:   required from here
/usr/include/CGAL/Triangulation_2.h:100:48: error: no type named ‘size_type’ in ‘struct CGAL::Default’
   typedef typename Tds::size_type              size_type;
                                                ^
/usr/include/CGAL/Triangulation_2.h:101:48: error: no type named ‘difference_type’ in ‘struct CGAL::Default’
   typedef typename Tds::difference_type        difference_type;
                                                ^
/usr/include/CGAL/Triangulation_2.h:103:48: error: no type named ‘Vertex’ in ‘struct CGAL::Default’
   typedef typename Tds::Vertex                 Vertex;
...
...
```

Only hint I can find is this stackoverflow [post](https://stackoverflow.com/questions/50516051/cant-compile-cgal-code) which suggests upgrading OS version.

**Comment by Yixin-Hu** [comment]
Did you try having CGAL example code compiled on your machine?

**Comment by GregVernon** [comment]
I noticed this this morning and have a fix.  The problem is that, as of right now, [Ubuntu 16.04 considers CGAL v 4.7-4 to be the current version](https://packages.ubuntu.com/xenial/libcgal-dev).  Here's how to fix:

1. Download CGAL source code: https://github.com/CGAL/cgal/releases 
2. Extract the source code (if necessary) from the zip/tar/xz file
3. Place the extracted folder ("cgal-releases-CGAL-4.12") in the `TetWild/extern/` directory
4. Rename the folder to `CGAL`
5. Set `CMAKE_PREFIX_PATH` environment variable to the path of the CGAL folder:
`export CMAKE_PREFIX_PATH=/path/to/TetWild/extern/:/path/to/TetWild/extern/CGAL/`
6. Rerun `cmake ..`
