### ISSUE TITLE
Error trying to compile on Ubuntu 16.04

### ISSUE THREAD

**Issue by bhallnz** [Yixin-Hu/TetWild#21]
Cmake completes without error and I've followed the instructions outlined in #2  for using cgal 4.12 in Ubuntu 16.04 but it fails with the following error:

```
[ 86%] Building CXX object CMakeFiles/libTetWild.dir/src/Preprocess.cpp.o
In file included from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Sqrt_extension.h:63:0,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/MP_Float.h:31,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Filtered_kernel.h:34,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Exact_predicates_exact_constructions_kernel.h:30,
                 from /usr/src/TetWild/src/heads.h:48,
                 from /usr/src/TetWild/src/Preprocess.h:15,
                 from /usr/src/TetWild/src/Preprocess.cpp:12:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Sqrt_extension/Algebraic_extension_traits.h: In member function ‘CGAL::Algebraic_extension_traits<CGAL::Sqrt_extension<NT, ROOT, ACDE_TAG, FP_TAG> >::Type CGAL::Algebraic_extension_traits<CGAL::Sqrt_extension<NT, ROOT, ACDE_TAG, FP_TAG> >::Denominator_for_algebraic_integers::operator()(InputIterator, InputIterator)’:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Sqrt_extension/Algebraic_extension_traits.h:134:38: error: ‘make_transform_iterator’ is not a member of ‘boost’
             Type a = std::accumulate(::boost::make_transform_iterator(begin,Standardise<Type>()), 
                                      ^
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Sqrt_extension/Algebraic_extension_traits.h:135:21: error: ‘make_transform_iterator’ is not a member of ‘boost’
                     ::boost::make_transform_iterator(end  ,Standardise<Type>()), Type(0));
                     ^
In file included from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/internal/Exact_type_selector.h:34:0,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Filtered_kernel.h:36,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Exact_predicates_exact_constructions_kernel.h:30,
                 from /usr/src/TetWild/src/heads.h:48,
                 from /usr/src/TetWild/src/Preprocess.h:15,
                 from /usr/src/TetWild/src/Preprocess.cpp:12:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Lazy_exact_nt.h: In member function ‘NT CGAL::INTERN_LAZY_EXACT_NT::Root_of_selector<NT, Functor>::Root_of::operator()(int, Input_iterator, Input_iterator) const’:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Lazy_exact_nt.h:845:31: error: ‘make_transform_iterator’ is not a member of ‘boost’
                               ::boost::make_transform_iterator( begin, cast ),
                               ^
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Lazy_exact_nt.h:846:31: error: ‘make_transform_iterator’ is not a member of ‘boost’
                               ::boost::make_transform_iterator( end, cast ) ) );
                               ^
In file included from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/point_generators_3.h:35:0,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Polygon_mesh_processing/internal/Side_of_triangle_mesh/Point_inside_vertical_ray_cast.h:30,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Side_of_triangle_mesh.h:30,
                 from /usr/src/TetWild/src/heads.h:86,
                 from /usr/src/TetWild/src/Preprocess.h:15,
                 from /usr/src/TetWild/src/Preprocess.cpp:12:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/point_generators_2.h: In constructor ‘CGAL::Random_points_in_triangles_2<Point_2, Triangle_2, Creator>::Random_points_in_triangles_2(const TriangleRange&, CGAL::Random&)’:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/point_generators_2.h:690:24: error: ‘make_transform_iterator’ is not a member of ‘boost’
     : Base(make_range( boost::make_transform_iterator(triangles.begin(), internal::Address_of<Triangle_2>()),
                        ^
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/point_generators_2.h:691:24: error: ‘make_transform_iterator’ is not a member of ‘boost’
                        boost::make_transform_iterator(triangles.end(), internal::Address_of<Triangle_2>()) ),
                        ^
In file included from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Polygon_mesh_processing/internal/Side_of_triangle_mesh/Point_inside_vertical_ray_cast.h:30:0,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Side_of_triangle_mesh.h:30,
                 from /usr/src/TetWild/src/heads.h:86,
                 from /usr/src/TetWild/src/Preprocess.h:15,
                 from /usr/src/TetWild/src/Preprocess.cpp:12:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/point_generators_3.h: In constructor ‘CGAL::Random_points_in_triangles_3<Point_3, Triangle_3, Creator>::Random_points_in_triangles_3(const TriangleRange&, CGAL::Random&)’:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/point_generators_3.h:682:24: error: ‘make_transform_iterator’ is not a member of ‘boost’
     : Base(make_range( boost::make_transform_iterator(triangles.begin(), internal::Address_of<Triangle_3>()),
                        ^
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/point_generators_3.h:683:24: error: ‘make_transform_iterator’ is not a member of ‘boost’
                        boost::make_transform_iterator(triangles.end(), internal::Address_of<Triangle_3>()) ),
                        ^
In file included from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Orthogonal_k_neighbor_search.h:29:0,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/internal/AABB_tree/AABB_search_tree.h:28,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/AABB_tree.h:33,
                 from /usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/Side_of_triangle_mesh.h:33,
                 from /usr/src/TetWild/src/heads.h:86,
                 from /usr/src/TetWild/src/Preprocess.h:15,
                 from /usr/src/TetWild/src/Preprocess.cpp:12:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/internal/K_neighbor_search.h: At global scope:
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/internal/K_neighbor_search.h:101:18: error: ‘transform_iterator’ in namespace ‘boost’ does not name a template type
   typedef boost::transform_iterator<Transform_pair,advanced_iterator> iterator;
                  ^
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/internal/K_neighbor_search.h:151:3: error: invalid use of template-name ‘CGAL::iterator’ without an argument list
   iterator begin() const
   ^
/usr/src/TetWild/extern/CGAL/lib/cmake/CGAL/../../../include/CGAL/internal/K_neighbor_search.h:156:3: error: invalid use of template-name ‘CGAL::iterator’ without an argument list
   iterator end() const
   ^
CMakeFiles/libTetWild.dir/build.make:62: recipe for target 'CMakeFiles/libTetWild.dir/src/Preprocess.cpp.o' failed
make[2]: *** [CMakeFiles/libTetWild.dir/src/Preprocess.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libTetWild.dir/all' failed
make[1]: *** [CMakeFiles/libTetWild.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2
```
This is the cmake output:

```
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to Release
-- Using header-only CGAL
-- Targetting Unix Makefiles
-- Using /usr/bin/c++ compiler.
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so  
-- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so  
-- __cplusplus is 199711
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Boost include dirs: /usr/include
-- Boost libraries:    /usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Using gcc version 4 or later. Adding -frounding-math
-- Found LIBIGL: /usr/src/TetWild/extern/libigl/include  
-- Using header-only CGAL
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Found CGAL: /usr/src/TetWild/extern/CGAL
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Could NOT find Matlab (missing:  Matlab_INCLUDE_DIRS Matlab_MEX_LIBRARY Matlab_MEX_EXTENSION Matlab_ROOT_DIR MEX_COMPILER MX_LIBRARY ENG_LIBRARY) 
-- Could NOT find MOSEK (missing:  MOSEK_LIBRARIES MOSEK_INCLUDE_DIR) 
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Creating target: igl::core
-- Found CGAL: /usr/src/TetWild/extern/CGAL
-- Creating target: igl::cgal
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Using local options file: /usr/src/TetWild/extern/geogram/CMakeOptions.txt
-- Configuring build for standalone Geogram (without Vorpaline)
-- GCC version >= 4.3, activating sign conversion warnings
-- GCC version >= 4.6, activating double promotion warnings
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/TetWild/build
```

**Comment by Yixin-Hu** [comment]
Hi,

Looks like boost or cgal problem.  Could you try reinstalling cgal? 

I'm using boost 1.62.0 and cgal 4.10 on Linux.
